model:
  name: SEGONE
  channel_in: 3
  channel_out: 13
  num_layers: 5
  kernel_size: 3
  pool_kernel_size: 3
  bottleneck_scale: 1
  bottleneck_repeat: 5

data:
  name: HEART
  datapath: ../data/msd_heart
  resolution:
    - 512
    - 512
  

train:
  cuda: true
  epoch: 1000
  learning_rate: 0.01
  lr_step: 500
  batch_size: 512
  num_workers: 8
  save_dir: exps
  load_weights: null
  load_optimizer: null
  load_encoder: null
  save_frequency: 30
  