model:
  name: SEGONE
  type: segmentation
  channel_in: 3
  channel_out: 38
  num_layers: 4
  kernel_size: 4
  pool_kernel_size: 4
  bottleneck_scale: 1
  bottleneck_repeat: 5
  bottleneck_channel: 32

data:
  name: PET
  datapath: data/oxford_pet
  train: train
  val: val
  resolution:
    - 512
    - 512

train:
  cuda: true
  epoch: 1000
  learning_rate: 0.003
  lr_step: 500
  batch_size: 8
  num_workers: 4
  save_dir: exps
  load_weights: null
  load_optimizer: null
  load_encoder: null
  save_frequency: 5
  