model:
  name: RESNET
  type: segmentation
  channel_in: 3
  channel_out: 4
  num_layers: 50
  kernel_size: 3

data:
  name: BRAIN
  datapath: data/msd_brain
  train: train
  val: train
  resolution:
    - 256
    - 256

train:
  cuda: true
  epoch: 200
  learning_rate: 0.0001
  lr_step: 5
  batch_size: 32
  num_workers: 4
  save_dir: exps
  load_weights: null
  load_optimizer: null
  load_encoder: null
  save_frequency: 5
  patience: 5